AWSTemplateFormatVersion: 2010-09-09
Parameters:

  BucketName:
    Type: String
    Default: my-s3-bucket-123456789012
    Description: S3 Bucket Name

Resources:

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: BucketName

Outputs:

  MyBucketName:
    Value: !Ref S3Bucket